### ISSUE TITLE
Incorrect time shown for recurring items

### ISSUE THREAD

**Issue by counterpoint** [wernerjoss/grav-plugin-fullcalendar#44] opened 2021-12-09 10:11 UTC
This can be verified by creating a calendar page and inserting the code:
`[fullcalendar icsfile="https://calendar.google.com/calendar/ical/pjb5747j5gn75hs223vms3bfng%40group.calendar.google.com/public/basic.ics"][/fullcalendar]`
This is a public calendar that should be accessible anywhere. There is an entry for a meeting at 7.30 pm on the second Wednesday of each month. Up to and including March 2021, it is shown correctly. From April 2021 onwards, it is shown incorrectly as 6.30 pm. This might be to do with the clock change on the last Sunday of March, although the time does not become correct again after the change is reversed on the last Sunday of October.

**Comment by ghost** [comment] 2021-12-09 23:06
It's even weirder for me (in Australia). Up to March 2021 it shows the meeting at 6:30am on Thursday (prob 7:30pm day before in your time). But from April 2021 it jumps back to 9:30am on the Wednesday.

**Comment by counterpoint** [comment] 2021-12-10 03:29
Correction. The entries that show correctly were individual entries. The recurring entry started in April 2021 and always shows one hour out, displaying as 6.30p whereas the calendar entry is for 19.30. Working from a Nextcloud calendar instead of Google gives correct time.

**Comment by counterpoint** [comment] 2021-12-10 03:30
Thanks for your comment @simplycomputing. Looks as if you probably see the individual entries correctly, but strange that the recurring entry differs by a larger amount than it does for me.

**Comment by ghost** [comment] 2021-12-10 04:25
Just tested this on my google calendar. I made a recurring test event at 9am and it shows on my website as 10pm - that is 10pm for _every_ month into the future. So I don't think it's a daylight saving issue at all. Seems more like a time zone anomaly.

For you it is one hour out, but for me it is 11 hours.

**Comment by ghost** [comment] 2021-12-10 04:27
But if I make a single event at 9am it shows correctly as 9am. So why is recurring treated differently??

**Comment by ghost** [comment] 2021-12-10 05:02
@counterpoint - what is the time difference compared to UTC where you are? For me, Sydney NSW is 11 hours ahead of Coordinated Universal Time so I suspect the recurring events are not being localised.

**Comment by wernerjoss** [comment] 2021-12-12 10:35
@simplycomputing , you are correct with your assumption that times for recurring events are currently not localized, see also the corresponding thread in the [forum](https://discourse.getgrav.org/t/calendar-shows-wrong-times-for-recurring-entry/19166/12).
meanwhile, I have found a version of the rrule.js library which is supposed to support timezones.
I have already fiddled with this, and got it to display correct times for timzones Europe/London and Europe/Berlin, but not out-of-the box (had to add an offset, which seems strange to me).
so, could you attach here an ics file with at least 1 recurring event for your timezone ?

**Comment by wernerjoss** [comment] 2021-12-12 11:11
> Correction. The entries that show correctly were individual entries. The recurring entry started in April 2021 and always shows one hour out, displaying as 6.30p whereas the calendar entry is for 19.30. Working from a Nextcloud calendar instead of Google gives correct time.

@counterpoint , can you provide an ICS file from Nextcloud (without private information) including a recurring event ?

**Comment by ghost** [comment] 2021-12-12 20:00
Here is a google calendar ics. For me it has a recurring event at 12pm on the first day of the month, and a recurring event on 2nd Tuesday of the month at 9am
[cogginsalan@gmail.com.ical.zip](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/7699471/cogginsalan%40gmail.com.ical.zip)
.

**Comment by ghost** [comment] 2021-12-12 20:03
My timezone is Sydney, Australia by the way. We are currently in daylight saving.

**Comment by wernerjoss** [comment] 2021-12-12 20:35
thanks, Alan,
a quick check with my current development state looks like this:
![grafik](https://user-images.githubusercontent.com/36265757/145728593-479bde2a-a72b-4d1c-8670-1eb1b7c9bbee.png)
which seems ok, so far.
I'll do some more testing and then commit the changes to master, so you can check it out for yourself.

**Comment by ghost** [comment] 2021-12-12 20:41
That looks good. But note the single test event has now jumped forward to previous day (should be 9am on the Wednesday).

**Comment by wernerjoss** [comment] 2021-12-12 20:49
hm, looking into the ics file shows DTSTART:20211214T220000Z for the single event,
which is Tuesday, 14th Dec. as shown.
however, the screenshot shows 23pm, should be 22pm - strange.
will have to do some more investigation, I guess :-)

**Comment by ghost** [comment] 2021-12-12 21:05
Yes, sorry. I should have said the single test event has jumped **back** to the previous day. Here is how the calendar looks for me:

![calendar](https://user-images.githubusercontent.com/46998578/145729515-a357c7a6-7a98-4523-be7a-1ca15e6309f7.png)

**Comment by wernerjoss** [comment] 2021-12-13 08:53
ok, I see - but, the ics data you sent has the following entrys for that single event:

  `
  BEGIN:VEVENT  
  DTSTART:20211214T220000Z  
  DTEND:20211214T230000Z  
  DTSTAMP:20211212T195632Z  
  UID:69agtn00l5dakldt2ieh9fj9rm@google.com  
  CREATED:20211210T042641Z  
  DESCRIPTION:<a href="https://simplycomputing.com.au" id="ow745" __is_owner=  
   "true">Link</a><br>This is a description.<br>It contains a link.<br><a href  
   ="https://simplycomputing.com.au">https://simplycomputing.com.au</a>  
  LAST-MODIFIED:20211210T052207Z  
  LOCATION:  
  SEQUENCE:0  
  STATUS:CONFIRMED  
  SUMMARY:test event single  
  TRANSP:OPAQUE  
  END:VEVENT  
  `
(the code display is badly formatted, line breaks are missing, sorry)

according to that, the day is tuesday 14th dec, not wednesday 15th dec.
plus, your google calendar shows 9am as time, instead of 10pm.
so, I guess, this could also be an UTC -> local time issue, as 10pm + 11h = 9am on next day.
a possible explanation would be:
- single events data is stored as UTC
- recurring events data is stored using local date/time
I'll see if this can be confirmed and how the plugin could deal with it.

**Comment by ghost** [comment] 2021-12-13 09:00
Oh dear. This sounds like a nightmare to sort out! Well, if you want to just say that your plugin doesn't handle recurring events I certainly wouldn't blame you. :-)

**Comment by wernerjoss** [comment] 2021-12-13 16:15
oh, well, I already thought about that, yes :smile:  - but I have meanwhile put so much time into this, I want it to get going, finally.
it seems now I had to add even more javascript stuff for timezone handling, and it looks like I'm on the right way, now:
![grafik](https://user-images.githubusercontent.com/36265757/145847513-4f587e6e-e97b-4a6c-987f-af94311fc216.png)
this is only an intermediate result with some things hard coded, but, at least, I guess it will work out.
I'll see how long that will take...

**Comment by wernerjoss** [comment] 2021-12-14 17:07
so, I have committed my latest improvements to master, which works for my Test cases here.
I had to use 2 different javascript librarys with integrated timezone support, one for single events, one for recurring events.
unfortunately, both libs do not exactly work the same way, so additional adaptions were necessary.
can you check if this works for you ?

**Comment by ghost** [comment] 2021-12-14 18:51
No, sorry to report not working. I created a new recurring event 6am every Wednesday. This is the google calendar compared to the grav calendar. As you can see both recurring and single are both out.

![google](https://user-images.githubusercontent.com/46998578/146061619-dcbaec98-2edc-4784-80b8-9ec7e73cf40c.png)

![grav](https://user-images.githubusercontent.com/46998578/146061214-22043760-8e00-4eac-ae56-b8595842185f.png)

**Comment by wernerjoss** [comment] 2021-12-14 20:08
ok, can you attach the ics file, please ?

**Comment by ghost** [comment] 2021-12-14 20:21
Here it is.
[cogginsalan@gmail.com.ical.zip](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/7714511/cogginsalan%40gmail.com.ical.zip)

**Comment by wernerjoss** [comment] 2021-12-14 20:31
thanks, this looks ok here:
![grafik](https://user-images.githubusercontent.com/36265757/146074748-39dfa0ca-6a4e-449f-b941-fe2d96cc3cbb.png)
maybe you did not clear the grav cache before loading the calendar ?
(and , to be sure, also clear the browser cache)

**Comment by ghost** [comment] 2021-12-14 20:44
I cleared the cache numerous times, and tried it on a different browser (also cleared that). Still the same. Does the timezone in the Grav settings affect this? I have mine set to Sydney, Australia. What is yours?

![timezone](https://user-images.githubusercontent.com/46998578/146076525-96c13d55-ec89-4d3d-82cf-e4762e751c75.png)

**Comment by ghost** [comment] 2021-12-14 20:52
Hmmm... this is getting crazy. If I put that ICS file in as a straight file calendar then I get this:

![cal2](https://user-images.githubusercontent.com/46998578/146077500-448d5b04-f72c-4ef6-acc9-9a1a1929200a.png)

**Comment by wernerjoss** [comment] 2021-12-14 20:53
well, I also thought about the grav config timezone setting, mine is Europe/Berlin, then I also tried Australia/Sydney:
no difference (as expected).
it looks to me as if you have still the old plugin version.
you can check this in your admin backend, under plugins.
fullcalendar should report v0.2.14 - if it shows 0.2.13, you still have the old version.

**Comment by ghost** [comment] 2021-12-14 20:54
![fullcalendar](https://user-images.githubusercontent.com/46998578/146077853-531bb3b6-20b0-4e18-a450-4e8e87f1a4d4.png)

**Comment by wernerjoss** [comment] 2021-12-14 20:57
hm, that seems ok.
so, I'm afraid I'm out of ideas, currently - sorry.
will think about this later on....

**Comment by ghost** [comment] 2021-12-14 20:59
Yeah. It seems like a mess of complications. Thanks for trying.

**Comment by wernerjoss** [comment] 2021-12-15 16:05
after some more investigation, I have now the impression that the timezone related javascript libs are just not working for you, although I have no clue why.
they should be visible in the javascript debugger like so:
![grafik](https://user-images.githubusercontent.com/36265757/146221459-428bd179-f284-4835-b64f-6159b4b93b5d.png)
can you confirm this ?

**Comment by ghost** [comment] 2021-12-15 20:07
Will check that.

I also think it is odd that I get different result when using the calendar link to when I put in the ics file. If you want to test this the direct link is: https://calendar.google.com/calendar/ical/cogginsalan%40gmail.com/public/basic.ics

**Comment by ghost** [comment] 2021-12-15 20:30
OK - found it. I have this
![debugger](https://user-images.githubusercontent.com/46998578/146260495-70447943-662c-41c3-90ad-8ee90d97a246.png)

**Comment by wernerjoss** [comment] 2021-12-15 20:41
yes, that is the right view - the js debugger is sometimes called Sources.
so, the relevant libraries show up to be loaded, which makes the whole thing even more obscure, as they obviously do not seem to work for you.
as for the difference calendar link <-> ics file I will check tomorrow.

**Comment by counterpoint** [comment] 2021-12-16 12:34
The calendar file I have been testing with is publicly available at https://thirskandmalton.greenparty.org.uk/calendar.ics. It displays correctly at https://thirskandmalton.greenparty.org.uk/calendar/ and is served by Nextcloud.

**Comment by counterpoint** [comment] 2021-12-16 12:50
You can see the Full Calendar display connected to Nextcloud and also connected to Google at https://calendar.bsr.cloud/. Curiously, the results are different. It appears that the recurring entry that is based on a fixed recurring date (Green Drinks on 5th of every month) displays correctly when feed from Nextcloud but not from Google. Whereas the recurring event based on the second Wednesday of each month (T&M GP Monthly Meeting) displays wrong in both.

**Comment by wernerjoss** [comment] 2021-12-19 17:59
> The calendar file I have been testing with is publicly available at https://thirskandmalton.greenparty.org.uk/calendar.ics. It displays correctly at https://thirskandmalton.greenparty.org.uk/calendar/ and is served by Nextcloud.

@counterpoint ,
I have now made some more investigations into this and it looks like the timezone librarys mentioned above are not aware if the month of the event's start date is within or out of the daylight saving time.
so, I guess I will have to determine that from the ics file, as this has a VTIMEZONE block with rules for daylight saving and for standard time.
my understanding so far was the timezone libs would handle that automatically, but they do not.
I'll work on that issue now, but no guarantee how long a solution will take :smile:

**Comment by counterpoint** [comment] 2021-12-21 13:35
Thanks @wernerjoss. It seems that the need for Javascript to produce a pretty calendar is throwing up a lot of issues. I was very disappointed that you closed the issue that the popups cannot be moused over. It's not just a matter of not being able to click on links (although that is certainly desirable), it's that you cannot even copy and paste them. If you are reliant on Javascript libraries, it's probably no help to you, but the PHP libraries used in your iCalendar plugin seem to work fine. I added some code to that plugin to pick out any weblinks in the event description, and also made location into a link to Google maps. And elaborated the display a little. The result can be seen at https://calendar.bsr.cloud/events-ical. It isn't as cute as a calendar, but it is a lot more functional. If the calendar can't be made to (a) show correct times and (b) allow for people to link to further information on events, I'm likely to use the event list for preference. I'll probably add a bit more code to fetch the ICS file dynamically (rather than with cron etc).

**Comment by wernerjoss** [comment] 2021-12-22 13:53
well, the icalendar plugin is just a simple list, not more.
everything that is more visually appealing, is nowadays based on javascript, or even on heavy librarys built upon it, like react.
if you like to share your icalendar modifications, you could just make a fork and publish that, evtl. including a pull request.
as for the rest, yes, I plan to get the timezone (incl. recurring events) issue resolved.

**Comment by counterpoint** [comment] 2021-12-22 14:07
@wernerjoss Yes, I appreciate it is "just" a simple list. But the purpose of a calendar is for people to see what events are planned, and to gain access to details in a useful way. I'm grateful for your efforts on the time problem, but at present the calendar is unusable as it displays incorrect times. Beyond that, from my point of view, a "simple" list that provides all the details of forthcoming events, including clickable links for online meetings or locations or whatever is a lot more user friendly than a calendar that doesn't provide those features. Yes, I'd use a calendar if one with the ICS Calendar functionality was available. But in its absence, my extended event list meets user requirements better. I will try to fork etc when time permits, although as a novice Grav developer I've yet to figure out whether it ought to work like iCalendar or should create its own template, or whether there are any other alternatives for a plugin. To be generally useful, I guess the styling should be parameterised too. BTW I've added the day of the week to each item now.

**Comment by wernerjoss** [comment] 2021-12-22 14:25
ok, @counterpoint ,
then lets just see what your and my improvements will lead to :smile: - also note it is easy to make a calendar page which combines fullcalendar and icalendar, e.g. icalendar using an [accordion](https://github.com/getgrav/grav-plugin-shortcode-ui),
thus it initially only occupies one line (which is easy to unfold and see the complete list).

**Comment by wernerjoss** [comment] 2022-01-04 14:36
so, finally, I'm back again with some news w.r to this issue, see the updated docs - Timezone issues.
unfortunately, as said there, I could not find an automatic solution.
but, with the now available tz_offset* settings, it should be possible to correctly display calendars from different timezones.
e.g., [this calendar](https://thirskandmalton.greenparty.org.uk/calendar.ics) works for me using the settings on the screenshot:
![grafik](https://user-images.githubusercontent.com/36265757/148074091-3292b315-fc20-429e-902c-03de5a90b0e5.png)
also note there is now a new setting for onClick Popups which will, if enabled, create a simple alert() window showing the event description, which is ugly, but, at least, text can be copied from :smile:

**Comment by ghost** [comment] 2022-01-04 21:45
Fantastic! That is an ideal solution since there seem to be so many variables. I'll test it out when I get a chance.

Thanks for all your work on this and Happy New Year!

**Comment by ghost** [comment] 2022-01-05 10:00
This is getting very close, but there is one little bug I found. If I use these settings...

![settings1](https://user-images.githubusercontent.com/46998578/148198264-4a304e5d-884c-4de0-ba6e-483bd17e037b.png)

I found I can get my calendar perfectly in sync with my Google calendar times. This is now all correct:

![test1](https://user-images.githubusercontent.com/46998578/148198358-231a3469-50d1-46c0-bbba-423b6e6a4c7a.png)

That's great. But I was testing what happened when I changed the single event setting. It actually affects both single and recurring.

![settings2](https://user-images.githubusercontent.com/46998578/148198528-470a595e-e97f-4c7b-acfb-a4c9db4eebac.png)

So this is the result. You see the single has correctly moved on 2 hours, but also the recurring has moved as well.

![test2](https://user-images.githubusercontent.com/46998578/148198639-4293f4e9-13f3-400c-a0d8-3a7436939587.png)

**Comment by ghost** [comment] 2022-01-05 10:09
Actually, it's not really much of a bug. I can get them changed any way I want by adjusting both values. So this will work:

![settings3](https://user-images.githubusercontent.com/46998578/148199818-e96d8a48-9276-45e3-a1ea-5753151dfec2.png)

You could always "fix" it by just changing the text on the first field to "Time Offset (hours) to correct **all** Events" :-)

Nice work!

**Comment by wernerjoss** [comment] 2022-01-05 14:30
ok, fine to see it is now working for you, too.
and, yes, corrections are not independent, the single events offset will also affect the recurring events, so, single should be adjusted first, then see what happens to recurring events and then correct those.
I'll update the docs accordingly.

**Comment by ghost** [comment] 2022-01-05 21:07
Ah, good. Then it's working perfectly. You just need to clarify that in the docs (and maybe the field name).

I think it's an excellent solution! It seemed like a nightmare trying to adjust your code to cater for every calendar and time handling. But this is simple and elegant.

**Comment by wernerjoss** [comment] 2022-01-06 17:18
well, I still think this solution is not ideal, as would be an automatic adjustment, but, at least, I hope it can solve the timezone Problem for most users.
and, as the corrections will have to be done only once, it is not a big effort, nor an ongoing one.
I think I will now improve the docs some more and then make a new release.
and thanks again for your patience during these iterations :smile:

**Comment by wernerjoss** [comment] 2022-01-08 18:44
I'm closing this now as there have been no more comments/reports.

**Closed as completed by wernerjoss** 2022-01-08 18:44 UTC

**Comment by s1-ranjan** [comment] 2022-01-28 10:40
@wernerjoss, as of now the only support for the hour part is been implemented to this plugin, can this plugin be extended for the minutes too, as I am located in the +5.30 time zone and this plugin is not showing the correct event timing in the calander.

**Comment by wernerjoss** [comment] 2022-01-29 17:38
hi @s1-ranjan - yes, the plugin does currently only support integer hour values for timezone corrections.
I'll look into this and see how at least 30 minutes intervals can be implemented (I don't think 1 minute steps will be necessary, I have never seen timezones that have other fractions than 30 minutes offset to UTC)

**Comment by s1-ranjan** [comment] 2022-02-18 14:16
Thanks, @wernerjoss for writing me, I would like to point out for Nepal time zone cause Nepal is having +5:45 hours offset, so it would be better to give a better fix so that this plugin has a better fix for everybody.

**Comment by wernerjoss** [comment] 2022-02-20 09:33
Hi @s1-ranjan ,
I have now added an Option to not only specify hours, but also minutes for the TZ Offset in git master, please check if this works for you.

**Comment by s1-ranjan** [comment] 2022-02-28 14:39
Hi @wernerjoss ,
I have tried but it shows it is giving "ParserError" with the devanagari script- Hindi (हंदी)

**Comment by wernerjoss** [comment] 2022-02-28 17:04
hi @s1-ranjan ,
I have no clue what devanagari script is - does that do something in a Grav 
Installation ?
if yes, can you deactivate it and try without ?

**Comment by s1-ranjan** [comment] 2022-03-01 06:24
Hi @wernerjoss,
Devanagri script is a language script, and it has nothing to do with the Grav, this script is been used to write a few Indian languages such as Hindi, Marathi, Sanskrit, and Nepali (as far as I am aware).
I am able to overcome the issue by reentering the events in the calendar, but the issue is prevailing with the whole day recurring events, it's being reflected one day ahead for the whole day events.

**Comment by wernerjoss** [comment] 2022-03-01 17:49
hm, strange - I am not sure if I understand right what you mean.
what do you mean by 'reentering the events in the calendar' ?
(normally, you should just have an ics calendar file that does not have to be changed).
then, are only recurring events a day ahead ?
what about recurring event with start/end time ?
single events (whole day or not) are ok ?
can you provide a sample ics file ?

**Comment by s1-ranjan** [comment] 2022-03-02 15:56
That was a typo error, "reentering the events in the calendar ?" I mean to say I have to re-enter the calendar events in my nextcloud calendar app and making those fresh entries fixed my issue. 
Well regarding the sample file I am including a sample CSV file along with the nextcloud calendar link https://my-cloud.0or1.xyz/index.php/apps/calendar/p/yQiTAwYicd3imXMr 
Please have a look for the month of January in the calendar.
[जयंती.ics.zip](https://github.com/wernerjoss/grav-plugin-fullcalendar/files/8170965/ics.zip)

**Comment by wernerjoss** [comment] 2022-03-06 18:37
you are right - all-day recurring events were shifted one day forward.
this has nothing to do with timezones, though.
I have committed a fix that will hopefully resolve this, please test.

**Comment by s1-ranjan** [comment] 2022-03-07 03:52
Thanks @wernerjoss , I have tested your latest fix and I confirm it's working with all-day recurring events.

**Comment by wernerjoss** [comment] 2022-03-07 16:32
ok - fine, thanks for testing + feedback.
I have now created a new release.
btw. if you like this plugin, you can give it a star :smile:
