### ISSUE TITLE
Does the iCal-URL function still work?

### ISSUE THREAD

**Issue by YamiDoesDev** [wernerjoss/grav-plugin-fullcalendar#51] opened 2022-04-27 11:00 UTC
Hey man,
before I begin: I really love your work and really would like to use this plugin for the project of my institution.

I tried to test some functions. Pasting the .ics-files into the page folder and then using 
```md
[fullcalendar][/fullcalendar]
```
did work without any problems.
Just using the following syntax
```md
[fullcalendar icsfile="https://felix.hs-furtwangen.de/ical/paggregated/blablabla/blabla.ics"][/fullcalendar]
[fullcalendar icsfile="https://calendar.google.com/calendar/ical/blablablablabla/public/basic.ics"][/fullcalendar]
```
didn't work at all. (I censored the links due to data privacy and stuff. Tell me, if you really need working links or anything). It just renders the raw Markdown text and nothing more. The browser as well doesn't seem to request the data of the URL..

I hereby wanted to ask, if the URL-syntax is still functioning or if I'm doing something wrong. 
If you need any further information, feel free to let me know. I couldn't find anything helpful to fix the issue myself, and I'm not even sure, if I overlooked the URL-parser in the source code.

Thanks in advance for any sort of answer.

**Comment by wernerjoss** [comment] 2022-04-28 17:39
well, your use case involves [CORS](https://developer.mozilla.org/de/docs/Web/HTTP/CORS) which can always be a source of problems - the plugin, however, has a built-in CORS-proxy, which will normally deal with that.
for further assistance, you can contact me via the contact form on my website, e.g. to submit a working link.

**Comment by YamiDoesDev** [comment] 2022-04-28 17:50
I will try to check, if I can find the issue about that on my side then. I'll probably contact you tomorrow, since I'm a little busy today and need to prepare working links.
Furthermore, I'm not sure, if I should close this issue now, so I just leave it open for a short while.

**Comment by wernerjoss** [comment] 2022-04-28 18:03
ok, just leave this issue open, as long as it is not resolved for you.
btw., I just checked for myself with a remote ics file, which works ok here, so the CORS proxy is still working.
(I only check this from time to time, as my own site only has local calendar files...)

**Comment by wernerjoss** [comment] 2022-05-02 14:51
after some private conversations, it turned out the issue is due to a special test environment (nginx...) which cannot be verified/tested here - the relevant webserver seems to block http requests through the plugin proxy.
a workaround, however has been proposed and will be tested.
I'm closing this now as it does not seem to affect real world implementations.

**Closed as completed by wernerjoss** 2022-05-02 14:51 UTC
