### ISSUE TITLE
Behaviour on click on event without url present

### ISSUE THREAD

**Issue by makrohard** [wernerjoss/grav-plugin-fullcalendar#34] opened 2021-07-31 13:53 UTC
When I click on an event (read from an ics-file), which has no URL present, the browser redirects to ./undefined, which results in a 404. 
Example: If my calendar url is https://example.com/blog/calendar, a click on an event without url present redirects to: https://example.com/blog/undefined

Observation: The events are wrapped in an anchor tag. In case an URL is specified, href="target" is present, when there's no url,  then there's no href either.

Expected behaviour: If no URL is present, a click on an event should have no effect.

**Comment by wernerjoss** [comment] 2021-08-02 16:01
hm,
I cannot reproduce this - just tried with my own calendar [here](https://hoernerfranzracing.de/werner/kalender) - there is an event Sommertreffen on August 14, which has no URL. a click on it has no effect, as supposed.

**Comment by makrohard** [comment] 2021-08-05 00:18
I can confirm, that this is not a problem of the fullcalendar plugin, but theme-related. The unwanted behaviour is not present in a plain grav installation.
I use the open-publishing-space-skeleton, which redirects clicks on anchor-tags without href to ./undefined. I'll try to find out how to change that.

P.S: Got the problem. Will be fixed in the next release of that theme. Definetly no fullcalendar-pugin-issue.

**Comment by wernerjoss** [comment] 2021-08-05 18:06
ok, fine to see you got it sorted out :smile: - so I'm closing this issue now.

**Closed as completed by wernerjoss** 2021-08-05 18:06 UTC
